export const COLOMBIA_CITIES = [
    'Armenia',
    'Apartadó',
    'Aguachica',
    'Aguazul',
    'Acacías',
    'Arjona',
    'Barrancabermeja',
    'Barranquilla',
    'Bello',
    'Bogotá',
    'Bucaramanga',
    'Buga',
    'Buenaventura',
    'Cajicá',
    'Calarcá',
    'Cali',
    'Cartagena',
    'Cartago',
    'Cereté',
    'Chía',
    'Chiquinquirá',
    'Chinchiná',
    'Ciénaga',
    'Codazzi',
    'Copacabana',
    'Corozal',
    'Cúcuta',
    'Dosquebradas',
    'Duitama',
    'Envigado',
    'Espinal',
    'Facatativá',
    'Florencia',
    'Floridablanca',
    'Fusagasugá',
    'Funza',
    'Fundación',
    'Girardot',
    'Girón',
    'Garzón',
    'Granada',
    'Honda',
    'Ibagué',
    'Ipiales',
    'Istmina',
    'Itagüí',
    'Jamundí',
    'La Dorada',
    'La Estrella',
    'La Tebaida',
    'La Virginia',
    'Lorica',
    'Los Patios',
    'Magangué',
    'Madrid',
    'Maicao',
    'Malambo',
    'Manizales',
    'Málaga',
    'Medellín',
    'Melgar',
    'Mitú',
    'Mocoa',
    'Montería',
    'Montenegro',
    'Mosquera',
    'Neiva',
    'Ocaña',
    'Palmira',
    'Pasto',
    'Pereira',
    'Piedecuesta',
    'Pitalito',
    'Popayán',
    'Providencia',
    'Puerto Asís',
    'Puerto Carreño',
    'Puerto Colombia',
    'Puerto Tejada',
    'Quibdó',
    'Riohacha',
    'Rionegro',
    'Sabanalarga',
    'Sabaneta',
    'Sahagún',
    'San Andrés',
    'San Gil',
    'San Juan del Cesar',
    'San Vicente del Caguán',
    'Santa Marta',
    'Santa Rosa de Cabal',
    'Santander de Quilichao',
    'Sincelejo',
    'Soacha',
    'Socorro',
    'Soledad',
    'Sogamoso',
    'Tulua',
    'Tunja',
    'Turbaco',
    'Turbo',
    'Tumaco',
    'Valledupar',
    'Villa del Rosario',
    'Villamaría',
    'Villanueva',
    'Villavicencio',
    'Yopal',
    'Yumbo',
    'Zipaquirá',
] as const;
